<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE content
[
<!--======================================== modify but don't delete ========================================-->
 <!ENTITY base "./">
 <!ENTITY title	"DotGNU keeping you from getting tangled in a .NET">
 <!ENTITY this "danger.html">
 <!ENTITY maintainer "&lt;a href=&quot;http://norbert.ch/&quot;&gt;Norbert Bollow&lt;/a&gt; &lt;a href=&quot;mailto:nb@SoftwareEconomics.biz&quot;&gt;&_lt_;nb@SoftwareEconomics.biz&_gt_;&lt;/a&gt;">
 <!ENTITY modtime "Sat August 23, 2003">
<!--======================================== modify but don't delete ========================================-->

<!--======================================== add custom entities here ========================================-->
<!--======================================== add custom entities here ========================================-->

<!--======================================== declared here, defined elsewhere ========================================-->

 <!-- First block: "Homepage" + Information that sells DotGNU to developers -->
 <!ENTITY nav.functionality "">
 <!ENTITY nav.freedom "">
 <!ENTITY nav.web_services "">
 <!ENTITY nav.auth "">
 <!ENTITY nav.innovation "">
 <!ENTITY nav.stereo "">
 <!ENTITY nav.acronyms "">
 <!ENTITY nav.testimonials "">
 <!ENTITY nav.win "">

 <!-- Second block: "Useful DotGNU Software" - Let the code talk -->
 <!ENTITY nav.phpgw "">
 <!ENTITY nav.pnet "">
 <!ENTITY nav.snapshots "">
 <!ENTITY nav.downloads "">
 <!ENTITY nav.debs "">

 <!-- Third block: DotGNU Developers Community -->
 <!ENTITY nav.lists "">
 <!ENTITY nav.wiki "">
 <!ENTITY nav.irc "">
 <!ENTITY nav.join "">

<!-- Fourth block: Advocacy -->
 <!ENTITY nav.advocacy "">
 <!ENTITY nav.posters "">

<!-- Fifth block: Misc Information -->
 <!ENTITY nav.arch "">
 <!ENTITY nav.projects "">
 <!ENTITY nav.pnet.lib.status "">
 <!ENTITY nav.pnet.lib.docs "">
 <!ENTITY nav.patent "">

 <!ENTITY nav.mail.pipermail "">
 <!ENTITY nav.mail "">
 <!ENTITY misc.gnu "">
 <!ENTITY misc.dotgnu "">
 <!ENTITY _lt_ "">
 <!ENTITY _gt_ "">
 <!ENTITY _quot_ "">
 <!ENTITY _apos_ "">
 <!ENTITY _amp_ "">
 <!ENTITY nbsp "">
 <!ENTITY copy "">
 <!ENTITY root "">
<!--======================================== declared here, defined elsewhere ========================================-->

<!--======================================== don't touch this stuff ========================================-->
 <!ELEMENT ul (li)+>
 <!ELEMENT ol (li)+>
 <!ELEMENT dl (dt|dd)+>
 <!ELEMENT dt (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT li (#PCDATA | include | br | em | strong | code | a | img | ul | ol | dl)*>
 <!ELEMENT dd (#PCDATA | include | br | em | strong | code | a | img | ul | ol | dl)*>
 <!ELEMENT blockquote (#PCDATA | include | br | em | strong | code | a | img | ul | ol | dl)*><!--no nesting blockquotes-->
 <!ELEMENT pre (#PCDATA | include | br | em | strong | code | a)*><!--no images in pre-->
 <!ELEMENT a (#PCDATA | include | br | em | strong | code | img)*><!--no nesting anchors-->
 <!ELEMENT content (#PCDATA | include | p | h1 | h2 | h3 | h4 | pre | blockquote)*><!--block elements only in top level-->
 <!ELEMENT p (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT em (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT strong (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT code (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT h1 (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT h2 (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT h3 (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT h4 (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT br EMPTY>
 <!ELEMENT img EMPTY>
 <!ELEMENT include EMPTY>
 <!ATTLIST a title CDATA #IMPLIED name NMTOKEN #IMPLIED href CDATA #IMPLIED>
 <!ATTLIST img src CDATA #REQUIRED alt CDATA #REQUIRED align (top|middle|bottom|left|right) #IMPLIED>
 <!ATTLIST include file CDATA #REQUIRED entry NMTOKEN #IMPLIED overwrite (true|false) #IMPLIED>
<!--======================================== don't touch this stuff ========================================-->
]>

<content>
<h1>
 DotGNU - Keeping You from Getting Tangled in a Net!
</h1>
<p>
 The DotGNU project was started in reaction to Microsoft's .NET strategy,
 for which it will be a complete replacement (and not just a Free Software
 implementation).  The goals are to provide to <a href="&nav.pnet;">reasonably
 compatible</a> system and then
 improve on what Microsoft is offering.
</p>
<p>
 We say: "Ok, MS you are pushing webservices and C# and IL because you want
 to catch everyone in your dotNET, but
 <a href="http://www.gnu.org/gnu/thegnuproject.html">GNU</a> is taking
 precisely that  technology and using it to <a href="freedom.html">set
 the world free</a> from your monopolies."
</p>
<h2>The Growing Influence of Microsoft Corp. in Academics</h2>
<p>
To a large extent, what the world of technology will look like
tomorrow is determined by what is researched and taught at universities
today.
<a href="http://www.google.com/search?q=cache:zJKCFEhLFNkJ:www.msnbc.com/news/956800.asp%3F0cv%3DTB10%26cp1%3D1+site:www.msnbc.com+%22Microsoft+Institute+of+Technology%3F%22&amp;ie=UTF-8">Microsoft
Corp. understands that very well, and is steadily working on increasing
mindshare for their .NET stuff among academics.</a>  It needs to be a
major focus of Free Software advocates to counteract this influence and
raise awareness of Free Software alternatives such as DotGNU.
</p>
<h2>Independent e-Commerce Threatened by .NET</h2>
<p>In the beginnings of the DotGNU project, we were concerned primarily
 <a href="#lock-in">about the vendor lock-in problem for webservices</a>
 and about Microsoft's plan
 to unleash a <include file="navlinks.xml" entry="hailstorm" /> which has
 in the meantime been dropped,
 <include file="navlinks.xml" entry="hailstorm.whynot" />.  Similar
 concerns that Microsoft Corp. is trying to catch all e-commerce in their
 .NET and lock everyone in are explained in the article
 <include file="navlinks.xml" entry="TemptedBy.Net" />
 by Richard Hillesley (Linux User No 15, Oct 2001, p. 15-21).  Even if
 their original plan for destroying most Microsoft-independent e-commerce
 has failed, since they have enough resources to try again and again,we
 cannot relax.   By contrast, the goal of DotGNU is to give computer
 users full freedom to use the internet as they want.  For example, the
 DotGNU approach to <a href="&nav.web_services;">"web services"</a> will
 make it possible for end users to run webservice software on their own
 PC, so that the users are not forced to migrate their data to the
 webservice servers.
</p>
<a name="lock-in">
<h2>The Vendor Lock-In Problem for Webservices</h2>
</a>
<p>
A major concern with webservices is that data which should properly
be under the control of the users of the server may be stored on
the webservice server.  This may result in the business problem of
vendor lock-in because this may make it difficult to move to a different
webservice vendor, or to move a service in-house which was previously
outsourced as a webservice.  The DotGNU webservices vision proposes a
solution to this <a href="web-services.html#data">remote data problem</a>.
</p>
<a name="lock-in">
<h2>Privacy Issues</h2>
</a>
<p>
 DotGNU will use a decentralized paradigm for authentication and
 authorization:  No single company, server or
 entity will control authentication.  This avoids privacy problems like
 those pointed out in
 <include file="navlinks.xml" entry="letter.epic.on.passport" />
</p>
<a name="security">
<h2>Security Issues</h2>
</a>
<p>
 One major advantage of DotGNU over closed-source software platforms
 like .NET is that everyone is welcome to inspect the full source
 code, so that security problems and be found and corrected much more
 quickly.  DotGNU will emphasize security, it will use encryption
 wherever possible to keep user data secure and hidden. (According to
 the article
 <include file="navlinks.xml" entry="risks.of.passport" />[2],
 Microsoft's approach has some fundamental problems in the area of
 security.  In fact it appears that
 <include file="navlinks.xml" entry="passport.data.is.cleartext" />,
 a huge security risk.)  Because of entirely unrelated, serious
 security problems,
 <include file="navlinks.xml" entry="ms.forced.disable.wallet" /> as
 Marc Slemko
 <include file="navlinks.xml" entry="published.wallet.exploit" />
</p>
<h2>No-one Else Is Challenging Microsoft</h2> 
<p>
 There are no real remaining traditional competitors to MS, and the US
 government recently failed to contain MS, so the field is left to us. MS has
 announced that it has "bet the company" on .NET, because "Webservices"
 represents the future, and Windows and MS Office will become progressively
 less important. So DotGNU stands between where MS is and where it wants to
 be. Therefore DotGNU and .Net represents the ultimate showdown between
 proprietary and Free Software.
</p>
<h1>Frequently Asked Questions</h1>
<h2>
 Isn't it foolish to try competing with Microsoft?
</h2>
<p>
 Just like it's the goal of the <a href="&misc.gnu;">GNU project</a>
 to create a complete operating system that makes it completely
 unnecessary to use a non-free operating system like e.g. Microsoft
 Windows, it's the goal of the DotGNU project to be a complete
 competitor to Microsoft's ".Net initiative".
</p>
<p>
 The DotGNU project will compete with Microsoft for end-users,
 business customers and developers.
</p>
<p>
 Microsoft Windows had a huge head start over GNU/Linux in terms
 of user-friendliness to end users.  In spite of Microsoft's vast
 resources, GNU/Linux is already better than Microsoft Windows in
 some areas, and catching up fast in most others.
</p>
<p>
 We believe that the same kind of success story is possible with
 the DotGNU project.  The main difference is that this time,
 Microsoft doesn't have such a big head start.
</p>
<h2>
 Why can't we just wait and see whether the effects of .NET are really
 so bad?
</h2>
<p>
 Read this <a href="http://users.hol.gr/~barbanis/cavafy/walls.html">warning
 written in 1896</a>.    It is often said that the price of freedom is
 eternal vigilance.<sup>3</sup> Unless we counter them, Microsoft's efforts
 are not only a threat to Free Software, they are also extremely
 dangerous tools in the hands of any Evil Government that wants
 to make their citizens unfree.
</p>
<h1>
 Your comments please...
</h1>
<p class="maincontent">
You are invited to add your comments concerning this
at <a href="http://wiki.dotgnu.org/WebsiteComments/danger">the appropriate
page of the DotGNU Wiki</a>
</p>
<p>
 &nbsp;
</p>
<h4>
 References:
</h4>
<ol>
 <li>Richard Hillesley:
  <include file="navlinks.xml" entry="TemptedBy.Net" />
  Linux User No 15, Oct 2001, p. 15-21.
 </li>
 <li>
  David P. Kormann and Aviel D. Rubin,
  <include file="navlinks.xml" entry="risks.of.passport" />,
  Elsevier Science Press, volume 33, pages 51-58, 2000.
 </li>
 <li>
  This truth was popularized by Thomas Jefferson (1743 - 1826).
  The original source seems to be a speech by John Philpot Curran,
  who said "It is the common fate of the indolent to see their
  rights become a prey to the active. The condition upon which God hath
  given liberty to man is eternal vigilance; which condition if he
  break, servitude is at once the consequence of his crime and the
  punishment of his guilt." - <em>John Philpot Curran: Speech upon the
  Right of Election, 1790. (Speeches. Dublin, 1808.)</em>
 </li>
</ol>
</content>
