<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE content
[
<!--======================================== modify but don't delete ========================================-->
 <!ENTITY base "./">
 <!ENTITY title	"DotGNU Downloads">
 <!ENTITY this "downloads.html">
 <!ENTITY maintainer "&lt;a href=&quot;http://norbert.ch/&quot;&gt;Norbert Bollow&lt;/a&gt; &lt;a href=&quot;mailto:nb@cisto.com&quot;&gt;&_lt_;nb@cisto.com&_gt_;&lt;/a&gt;">
 <!ENTITY modtime "Mon July 7, 2003">
<!--======================================== modify but don't delete ========================================-->

<!--======================================== add custom entities here ========================================-->
<!--======================================== add custom entities here ========================================-->

<!--======================================== declared here, defined elsewhere ========================================-->
 <!ENTITY nav.snapshots "">
 <!ENTITY nav.rationale "">
 <!ENTITY nav.info "">
 <!ENTITY nav.debs "">
 <!ENTITY nav.faq "">
 <!ENTITY nav.essays "">
 <!ENTITY nav.proposals "">
 <!ENTITY nav.patent "">
 <!ENTITY nav.projects "">
 <!ENTITY nav.proposals.active "">
 <!ENTITY nav.arch "">
 <!ENTITY nav.see "">
 <!ENTITY nav.phpgw "">
 <!ENTITY nav.pnet "">
 <!ENTITY nav.pnet.lib.status "">
 <!ENTITY nav.pnet.lib.docs "">
 <!ENTITY nav.web_services "">
 <!ENTITY nav.auth "">
 <!ENTITY nav.mail.lists "">
 <!ENTITY nav.mail.pipermail "">
 <!ENTITY nav.mail.announce "">
 <!ENTITY nav.mail.developers "">
 <!ENTITY nav.mail.auth "">
 <!ENTITY nav.mail.arch "">
 <!ENTITY nav.mail.biz "">
 <!ENTITY nav.mail.website "">
 <!ENTITY misc.freedev "">
 <!ENTITY misc.gnu "">
 <!ENTITY misc.dotgnu "">
 <!ENTITY mail.gnu "">
 <!ENTITY mail.dotgnu "">
 <!ENTITY mail.rhysw "">
 <!ENTITY mail.gopal "">
 <!ENTITY mail.minten "">
 <!ENTITY mail.dnicol "">
 <!ENTITY _lt_ "">
 <!ENTITY _gt_ "">
 <!ENTITY _quot_ "">
 <!ENTITY _apos_ "">
 <!ENTITY _amp_ "">
 <!ENTITY nbsp "">
 <!ENTITY copy "">
 <!ENTITY root "">
<!--======================================== declared here, defined elsewhere ========================================-->

<!--======================================== don't touch this stuff ========================================-->
 <!ELEMENT ul (li)+>
 <!ELEMENT ol (li)+>
 <!ELEMENT dl (dt|dd)+>
 <!ELEMENT dt (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT li (#PCDATA | include | br | em | strong | code | a | img | ul | ol | dl)*>
 <!ELEMENT dd (#PCDATA | include | br | em | strong | code | a | img | ul | ol | dl)*>
 <!ELEMENT blockquote (#PCDATA | include | br | em | strong | code | a | img | ul | ol | dl)*><!--no nesting blockquotes-->
 <!ELEMENT pre (#PCDATA | include | br | em | strong | code | a)*><!--no images in pre-->
 <!ELEMENT a (#PCDATA | include | br | em | strong | code | img)*><!--no nesting anchors-->
 <!ELEMENT content (#PCDATA | include | p | h1 | h2 | h3 | h4 | pre | blockquote)*><!--block elements only in top level-->
 <!ELEMENT p (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT em (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT strong (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT code (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT h1 (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT h2 (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT h3 (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT h4 (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT br EMPTY>
 <!ELEMENT img EMPTY>
 <!ELEMENT include EMPTY>
 <!ATTLIST a title CDATA #IMPLIED name NMTOKEN #IMPLIED href CDATA #IMPLIED>
 <!ATTLIST img src CDATA #REQUIRED alt CDATA #REQUIRED align (top|middle|bottom|left|right) #IMPLIED>
 <!ATTLIST include file CDATA #REQUIRED entry NMTOKEN #IMPLIED overwrite (true|false) #IMPLIED>
<!--======================================== don't touch this stuff ========================================-->
]>

<content>
<h1>DotGNU Downloads</h1>
<p class="maincontent">
	The DotGNU project is a meta-project with a number of subprojects.
	This page serves as a one-stop spot to obtain all the available
	downloads for the DotGNU project. Also it provides a mirror for the
	source tarballs of some of the project releases. We will in the
	future also list other free-software projects supported by DotGNU.
</p>
<h2> Contributing </h2>
<p class="maincontent">
	These packages are built by various part-time volunteers of the 
	project. If you are interested in packaging DotGNU for any particular
	platform or distribution ,please contact the DotGNU
	<a href="mailto:developers@dotgnu.org">developers</a> mailing list. 
	The releases are usually on weekends , so volunteers have enough time to
	provide packages . The packages will generally be slightly delayed, 
	please bear with us.
</p>
<h2>DotGNU Portable.Net 0.5.10</h2>
<p class="maincontent">
	The Portable.net 0.5.10 tarballs are available from
	<a href="ftp://ftp.gnu.org/gnu/dotgnu/pnet/">ftp.gnu.org</a>
	and from <a href="http://www.southern-storm.com.au/portable_net.html">
	Southern Storm</a>.  GnuPG-signed md5sums are at the end of the
	<a href="http://dotgnu.org/pipermail/developers/2003-June/011079.html">release announcement</a>.
	<h3 class="maincontent">Source</h3>

	<ul class="maincontent">
		<li><a class="linksbody" href="http://ftp.gnu.org/gnu/dotgnu/pnet/pnet-0.5.10.tar.gz">pnet-0.5.10</a></li>
		<li><a class="linksbody" href="http://ftp.gnu.org/gnu/dotgnu/pnet/pnetlib-0.5.10.tar.gz">pnetlib-0.5.10</a></li>
		<li><a class="linksbody" href="http://ftp.gnu.org/gnu/dotgnu/pnet/pnetC-0.5.10.tar.gz">pnetC-0.5.10</a></li>
		<li><a class="linksbody" href="http://ftp.gnu.org/gnu/dotgnu/pnet/ml-pnet-0.5.10.tar.gz">ml-pnet-0.5.10</a></li>
		<li><a class="linksbody" href="http://ftp.gnu.org/gnu/dotgnu/pnet/treecc-0.2.6.tar.gz">treecc-0.2.6</a></li>
		<li><a class="linksbody" href="http://ftp.gnu.org/gnu/dotgnu/pnet/pnetmark-0.0.6.tar.gz">pnetmark-0.0.6</a></li>
		<li><a class="linksbody" href="http://ftp.gnu.org/gnu/dotgnu/pnet/pnetcurses-0.0.2.tar.gz">pnetcurses-0.0.2</a></li>
	</ul>

	<h3 class="maincontent">Debs</h3>
		
	<p class="maincontent">
		The location of the binaries is 
		<a href="ftp://ftp.gnu.org/gnu/dotgnu/pnet/debian/">
		ftp.gnu.org</a>. Use these for apt-get support.
		<pre class="maincontent">deb ftp://ftp.gnu.org/gnu/dotgnu/pnet/debian ./ 
deb-src ftp://ftp.gnu.org/gnu/dotgnu/pnet/debian ./
		</pre>
	</p>
	
	<h3 class="maincontent">Rpms</h3>

	<p class="maincontent">
		<a href="http://csserver.evansville.edu/~sc87/pnet-rpm/">Mandrake Rpms
		</a>
		of Pnet 0.5.10 have been built by Stephen Compall (s11 AT member.fsf.org).
	</p>

	<p class="maincontent">
		Source RPMS for Redhat have been built by Phillip Compton (
		pcompton AT proteinmedia.com) as part of the 
		<a href="http://fedora.us/">Fedora</a> project.
	</p>
	<p>
		The Redhat 9.0 RPMs have entered <a href="http://fedora.us/QA/">Fedora QA</a>.
	</p>
	<!--
	<ul class="maincontent">
	<li>
		<a class="linksbody" 
		href="http://download.fedora.us/fedora/redhat/9/i386/RPMS.stable/pnet-compiler-0.5.8-0.fdr.5.rh90.i386.rpm">pnet-compiler-0.5.8-0.fdr.5.rh90.i386.rpm</a>
	</li>
	<li>
		<a class="linksbody" 
		href="http://download.fedora.us/fedora/redhat/9/i386/RPMS.stable/pnet-embed-devel-0.5.8-0.fdr.5.rh90.i386.rpm">pnet-embed-devel-0.5.8-0.fdr.5.rh90.i386.rpm</a>
	</li>
	<li>
		<a class="linksbody" 
		href="http://download.fedora.us/fedora/redhat/9/i386/RPMS.stable/pnet-interpreter-0.5.8-0.fdr.5.rh90.i386.rpm">pnet-interpreter-0.5.8-0.fdr.5.rh90.i386.rpm</a>
	</li>
	<li>
		<a class="linksbody" 
		href="http://download.fedora.us/fedora/redhat/9/i386/RPMS.stable/pnet-libgc-0.5.8-0.fdr.5.rh90.i386.rpm">pnet-libgc-0.5.8-0.fdr.5.rh90.i386.rpm</a>
	</li>
	<li>
		<a class="linksbody" 
		href="http://download.fedora.us/fedora/redhat/9/i386/RPMS.stable/pnet-tools-0.5.8-0.fdr.5.rh90.i386.rpm">pnet-tools-0.5.8-0.fdr.5.rh90.i386.rpm</a>
	</li>
	<li>
		<a class="linksbody" 
		href="http://download.fedora.us/fedora/redhat/9/i386/RPMS.stable/pnetc-0.5.8-0.fdr.2.rh90.noarch.rpm">pnetc-0.5.8-0.fdr.2.rh90.noarch.rpm</a>
	</li>
	<li>
		<a class="linksbody" 
		href="http://download.fedora.us/fedora/redhat/9/i386/RPMS.stable/pnetlib-0.5.8-0.fdr.2.rh90.i386.rpm">pnetlib-0.5.8-0.fdr.2.rh90.i386.rpm</a>
	</li>
	</ul>

	<p class="maincontent"> Redhat SRPMS </p>

	<ul class="maincontent">	
	<li>
		<a class="linksbody" 
		href="http://download.fedora.us/fedora/redhat/9/i386/SRPMS.stable/pnet-0.5.8-0.fdr.5.rh90.src.rpm">pnet-0.5.8-0.fdr.5.rh90.src.rpm</a>
	</li>
	<li>
		<a class="linksbody" 
		href="http://download.fedora.us/fedora/redhat/9/i386/SRPMS.stable/pnetc-0.5.8-0.fdr.3.rh90.src.rpm">pnetc-0.5.8-0.fdr.2.rh90.src.rpm</a>
	</li>
	<li>
		<a class="linksbody" 
		href="http://download.fedora.us/fedora/redhat/9/i386/SRPMS.stable/pnetlib-0.5.8-0.fdr.2.rh90.src.rpm">pnetlib-0.5.8-0.fdr.2.rh90.src.rpm</a>
	</li>
	</ul>
	-->
	<p class="maincontent">
	<code>apt for rpm or yum </code> users can refer to the 
	<a href="http://www.fedora.us/wiki/FedoraHOWTO"> Fedora Howto </a>
	pages.	
	</p>
	<p class="maincontent">
	</p>
	
	<h3 class="maincontent">Gentoo Ebuilds</h3>
	<p class="maincontent">
		Rainer Groesslinger (rainer.groesslinger AT gmx DOT net) has
		contributed ebuild rules to the Gentoo portage directory. The
		ebuilds are available from Gentoo to build off our gnu.org mirrors.
		<ul class="maincontent">
		 <li><a href="http://www.gentoo.org/cgi-bin/viewcvs.cgi/dev-util/treecc/">http://www.gentoo.org/cgi-bin/viewcvs.cgi/dev-util/treecc/</a></li>
		<li>
			<a href="http://www.gentoo.org/cgi-bin/viewcvs.cgi/dev-dotnet/pnet/">http://www.gentoo.org/cgi-bin/viewcvs.cgi/dev-dotnet/pnet/</a>	
		</li>
	
		<li>
			<a href="http://www.gentoo.org/cgi-bin/viewcvs.cgi/dev-dotnet/pnetlib/">http://www.gentoo.org/cgi-bin/viewcvs.cgi/dev-dotnet/pnetlib/</a>
		</li>

		<li>
			<a href="http://www.gentoo.org/cgi-bin/viewcvs.cgi/dev-dotnet/pnetc/">http://www.gentoo.org/cgi-bin/viewcvs.cgi/dev-dotnet/pnetc/</a>
		</li>
		<li><a href="http://www.gentoo.org/cgi-bin/viewcvs.cgi/dev-dotnet/ml-pnet/">http://www.gentoo.org/cgi-bin/viewcvs.cgi/dev-dotnet/ml-pnet/</a></li>
		</ul>
	</p>
	
	<h3 class="maincontent">Binaries for the Microsoft Windows system</h3>
		
	<p class="maincontent">
		Thong Nguyen (tum AT verdicus DOT com) has zipped up his build
		version of the 0.5.10 release until the installers are built.
		The single .zip file contains both pnet and pnetlib.
	<!--
		Robert Johnson (bobjohnson11 AT yahoo DOT com) has built the 
		Portable.net system and the
		treecc tool for the Microsoft Windows system. They are
		available as installers. -->
	</p>

	<p class="maincontent">
		<ul class="maincontent">
		<li><a href="http://tummy.veridicus.com/tummy/programming/pnet/downloads/pnet_mingw_0_5_10.zip">pnet_mingw_0_5_10.zip</a></li>
		</ul>
	</p>
	<p class="maincontent">
		The Windows installers will become available as soon as they are built.
	<!--
		<ul class="maincontent">
		<li><a href="http://download.freedom.biz/contrib/bobj/TREECC-0-2-6-Installer.exe">treecc 0.2.6</a></li>
		<li><a href="http://download.freedom.biz/contrib/bobj/PNET-0-5-8-Installer.exe">Portable.NET 0.5.8</a></li>
		</ul>
	-->
	</p>

	<h3 class="maincontent"> Mac OS X Packages </h3>
	<p class="maincontent">
		The Mac .pkg files will become available as soon as they are 
		built.
	</p>
</p>
<h2> Phpgroupware 0.9.14 </h2>
<p class="maincontent">
	The Phpgroupware team has been working on their admirable webservices
	package and have rolled out their 0.9.14.002 release. They have a lot
	of packages, so visit their 
	<a href="http://www.phpgroupware.org/downloads">download section</a>.
	Phpgroupware is part of the DotGNU webservices project and supports
	major webservice protocols.
</p>
<h2>DotGNU Execution Environment 0.1.4</h2>
<p class="maincontent">
	The DGEE is an appserver which currently uses the Portable.Net
	runtime to execute the services. The DGEE is centered around its
	own <a href="http://savannah.gnu.org/projects/dgee">Savannah project
	</a>. DGEE uses Apache to manage HTTP traffic for its xmlrpc frontends.
	GnuPG-signed md5sums are <a href="http://dotgnu.org/pipermail/developers/2003-March/010326.html">here</a>.
</p>
<h3 class="maincontent">Source</h3> 
<ul class="maincontent">
	<li><a class="linkbody" href="http://www.nfluid.com/download/src/phlib-1.18.tgz">phlib-1.18.tgz</a></li>
	<li><a class="linkbody" href="http://www.nfluid.com/download/src/goldwater-0.3.4.tgz">goldwater-0.3.4.tgz</a></li>
	<li><a class="linkbody" href="http://www.nfluid.com/download/src/dgee-0.1.4.tgz">dgee-0.1.4.tgz</a></li>
</ul>
<h3 class="maincontent">Debs</h3>
	<p class="maincontent">
		Still waiting for them.
	</p>
<h3 class="maincontent">RPMS</h3>
	<p class="maincontent">
		With the dependencies ..
	</p>
<ul class="maincontent">
	<li><a class="linkbody" href="http://www.nfluid.com/download/rpm/phlib-1.18-0.1.i386.rpm">phlib-1.18-0.1.i386.rpm</a></li>
	<li><a class="linkbody" href="http://www.nfluid.com/download/rpm/phlib-1.18-0.1.src.rpm">phlib-1.18-0.1.src.rpm</a></li>
	<li><a class="linkbody" href="http://www.nfluid.com/download/rpm/goldwater-0.3.4-0.0.1.i386.rpm">goldwater-0.3.4-0.0.1.i386.rpm</a></li>
	<li><a class="linkbody" href="http://www.nfluid.com/download/rpm/goldwater-0.3.4-0.0.1.src.rpm">goldwater-0.3.4-0.0.1.src.rpm</a></li>
	<li><a class="linkbody" href="http://www.nfluid.com/download/rpm/dgee-0.1.4-0.0.1.i386.rpm">dgee-0.1.4-0.0.1.i386.rpm</a></li>
	<li><a class="linkbody" href="http://www.nfluid.com/download/rpm/dgee-0.1.4-0.0.1.src.rpm">dgee-0.1.4-0.0.1.src.rpm</a></li>
</ul>
<h2>DotGNU Forum</h2>
<p class="maincontent">
	Still awaiting a release.
</p>

<h2>Macs@Freport</h2>
<p class="maincontent">
	Release 0.6 is available for download from <a href="http://macs.sf.net">
	Macs SourceForge Project</a>.
</p>
<h2>Other projects</h2>
<p class="maincontent">
	This will be filled in as each project announces it's status and uploads
	the appropriate tarballs to the website.
</p>
<h2>
 Your comments please...
</h2>
<p class="maincontent">
You are invited to add your comments concerning this page
at <a href="http://wiki.dotgnu.org/WebsiteComments/downloads">the appropriate
page of the DotGNU Wiki</a>
</p>
</content>
