<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE content
[
<!--======================================== modify but don't delete ========================================-->
 <!ENTITY base "./">
 <!ENTITY title	"#dotgnu irc channel of the DotGNU Project">
 <!ENTITY this "irc.html">
 <!ENTITY maintainer "&lt;a href=&quot;http://norbert.ch/&quot;&gt;Norbert Bollow&lt;/a&gt; &lt;a href=&quot;mailto:nb@cisto.com&quot;&gt;&_lt_;nb@cisto.com&_gt_;&lt;/a&gt;">
 <!ENTITY modtime "Fri March 14, 2003">
<!--======================================== modify but don't delete ========================================-->

<!--======================================== add custom entities here ========================================-->
<!--======================================== add custom entities here ========================================-->

<!--======================================== declared here, defined elsewhere ========================================-->

 <!-- First block: "Homepage" + Information that sells DotGNU to developers -->
 <!ENTITY nav.functionality "">
 <!ENTITY nav.freedom "">
 <!ENTITY nav.web_services "">
 <!ENTITY nav.auth "">
 <!ENTITY nav.innovation "">
 <!ENTITY nav.stereo "">
 <!ENTITY nav.acronyms "">
 <!ENTITY nav.testimonials "">
 <!ENTITY nav.win "">

 <!-- Second block: "Useful DotGNU Software" - Let the code talk -->
 <!ENTITY nav.phpgw "">
 <!ENTITY nav.pnet "">
 <!ENTITY nav.snapshots "">
 <!ENTITY nav.downloads "">
 <!ENTITY nav.debs "">

 <!-- Third block: DotGNU Developers Community -->
 <!ENTITY nav.lists "">
 <!ENTITY nav.wiki "">
 <!ENTITY nav.irc "">
 <!ENTITY nav.join "">

<!-- Fourth block: Advocacy -->
 <!ENTITY nav.advocacy "">
 <!ENTITY nav.posters "">

<!-- Fifth block: Misc Information -->
 <!ENTITY nav.arch "">
 <!ENTITY nav.projects "">
 <!ENTITY nav.pnet.lib.status "">
 <!ENTITY nav.pnet.lib.docs "">
 <!ENTITY nav.patent "">

 <!ENTITY misc.gnu "">
 <!ENTITY misc.dotgnu "">
 <!ENTITY _lt_ "">
 <!ENTITY _gt_ "">
 <!ENTITY _quot_ "">
 <!ENTITY _apos_ "">
 <!ENTITY _amp_ "">
 <!ENTITY nbsp "">
 <!ENTITY copy "">
 <!ENTITY root "">
<!--======================================== declared here, defined elsewhere ========================================-->

<!--======================================== don't touch this stuff ========================================-->
 <!ELEMENT ul (li)+>
 <!ELEMENT ol (li)+>
 <!ELEMENT dl (dt|dd)+>
 <!ELEMENT dt (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT li (#PCDATA | include | br | em | strong | code | a | img | ul | ol | dl)*>
 <!ELEMENT dd (#PCDATA | include | br | em | strong | code | a | img | ul | ol | dl)*>
 <!ELEMENT blockquote (#PCDATA | include | br | em | strong | code | a | img | ul | ol | dl)*><!--no nesting blockquotes-->
 <!ELEMENT pre (#PCDATA | include | br | em | strong | code | a)*><!--no images in pre-->
 <!ELEMENT a (#PCDATA | include | br | em | strong | code | img)*><!--no nesting anchors-->
 <!ELEMENT content (#PCDATA | include | p | h1 | h2 | h3 | h4 | pre | blockquote)*><!--block elements only in top level-->
 <!ELEMENT p (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT em (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT strong (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT code (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT h1 (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT h2 (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT h3 (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT h4 (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT br EMPTY>
 <!ELEMENT img EMPTY>
 <!ELEMENT include EMPTY>
 <!ATTLIST a title CDATA #IMPLIED name NMTOKEN #IMPLIED href CDATA #IMPLIED>
 <!ATTLIST img src CDATA #REQUIRED alt CDATA #REQUIRED align (top|middle|bottom|left|right) #IMPLIED>
 <!ATTLIST include file CDATA #REQUIRED entry NMTOKEN #IMPLIED overwrite (true|false) #IMPLIED>
<!--======================================== don't touch this stuff ========================================-->
]>

<content>
<h1>DotGNU IRC Channel</h1>
<p>
The irc channel <code>#dotgnu</code> on <code>irc.freenode.net</code>
is one of the main communication tools of the DotGNU project.
</p>
<p>
 The logs of <code>#dotgn</code>u are always available here:
 <include file="navlinks.xml" entry="irc.dotgnu.logs" />
</p>
<h2>
 Weekly IRC Meetings
</h2>
<p>
 DotGNU holds weekly meetings to discuss any issues
 of relevance; to allow the developers to catch up
 with each other; and to allow new members to ask
 questions and find out how to join in.
</p>
<p>
 The meetings are conducted via IRC in the channel
 times:
</p>
<pre>
    Saturday 1000 UTC
    Saturday 2200 UTC
</pre>
<p>
 Note: the times are UTC, not GMT. If you use the GNU 
 operating system (e.g. GNU/Linux, the popular combination 
 of the GNU system with the kernel called Linux) or a Unix 
 system, then the command "date; date -u" will give you
 your current time in both local and UTC, allowing
 you do determine when the next meeting will occur.
</p>
<h2>
<code>#dotgnu</code> Channel Rules
</h2>
<ol>
<li>Treat everyone with kindness, even if you don't like what they say.</li>
<li>When there is an active on-topic conversation (i.e. something that
concerns the DotGNU project, or some of its development projects),
you are welcome to contribute in a constructive manner, but please don't
otherwise interrupt the conversation.</li>
<li>If necessary, the above rules will be enforced by means of channel
moderation.</li>
<li>When there is no active on-topic conversation, off-topic chatter is
welcome.  (Building good relationships between DotGNU people is beneficial
to the project).  Such off-topic chatter may be interrupted by serious
DotGNU-related discussion at any time.</li>
</ol>
<h2>
 Your comments please...
</h2>
<p class="maincontent">
You are invited to add your comments concerning this
at <a href="http://wiki.dotgnu.org/WebsiteComments/irc">the appropriate
page of the DotGNU Wiki</a>.
</p>
</content>
