<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE content
[
<!--======================================== modify but don't delete ========================================-->
 <!ENTITY base "./">
 <!ENTITY title	"DotGNU Project">
 <!ENTITY this "index.html">
 <!ENTITY maintainer "&lt;a href=&quot;http://norbert.ch/&quot;&gt;Norbert Bollow&lt;/a&gt; &lt;a href=&quot;mailto:nb@cisto.com&quot;&gt;&_lt_;nb@cisto.com&_gt_;&lt;/a&gt;">
 <!ENTITY modtime "Sun Oct 20 02:03:09 UTC 2002">
<!--======================================== modify but don't delete ========================================-->

<!--======================================== add custom entities here ========================================-->
<!--======================================== add custom entities here ========================================-->

<!--======================================== declared here, defined elsewhere ========================================-->
 <!ENTITY nav.snapshots "">
 <!ENTITY nav.rationale "">
 <!ENTITY nav.info "">
 <!ENTITY nav.debs "">
 <!ENTITY nav.faq "">
 <!ENTITY nav.essays "">
 <!ENTITY nav.proposals "">
 <!ENTITY nav.patent "">
 <!ENTITY nav.projects "">
 <!ENTITY nav.proposals.active "">
 <!ENTITY nav.arch "">
 <!ENTITY nav.see "">
 <!ENTITY nav.phpgw "">
 <!ENTITY nav.pnet "">
 <!ENTITY nav.pnet.lib.status "">
 <!ENTITY nav.pnet.lib.docs "">
 <!ENTITY nav.web_services "">
 <!ENTITY nav.auth "">
 <!ENTITY nav.mail.lists "">
 <!ENTITY nav.mail.pipermail "">
 <!ENTITY nav.mail.announce "">
 <!ENTITY nav.mail.developers "">
 <!ENTITY nav.mail.auth "">
 <!ENTITY nav.mail.arch "">
 <!ENTITY nav.mail.biz "">
 <!ENTITY nav.mail.website "">
 <!ENTITY misc.freedev "">
 <!ENTITY misc.gnu "">
 <!ENTITY misc.dotgnu "">
 <!ENTITY mail.gnu "">
 <!ENTITY mail.dotgnu "">
 <!ENTITY mail.rhysw "">
 <!ENTITY mail.gopal "">
 <!ENTITY mail.minten "">
 <!ENTITY mail.dnicol "">
 <!ENTITY _lt_ "">
 <!ENTITY _gt_ "">
 <!ENTITY _quot_ "">
 <!ENTITY _apos_ "">
 <!ENTITY _amp_ "">
 <!ENTITY nbsp "">
 <!ENTITY copy "">
 <!ENTITY root "">
<!--======================================== declared here, defined elsewhere ========================================-->

<!--======================================== don't touch this stuff ========================================-->
 <!ELEMENT ul (li)+>
 <!ELEMENT ol (li)+>
 <!ELEMENT dl (dt|dd)+>
 <!ELEMENT dt (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT li (#PCDATA | include | br | em | strong | code | a | img | ul | ol | dl)*>
 <!ELEMENT dd (#PCDATA | include | br | em | strong | code | a | img | ul | ol | dl)*>
 <!ELEMENT blockquote (#PCDATA | include | br | em | strong | code | a | img | ul | ol | dl)*><!--no nesting blockquotes-->
 <!ELEMENT pre (#PCDATA | include | br | em | strong | code | a)*><!--no images in pre-->
 <!ELEMENT a (#PCDATA | include | br | em | strong | code | img)*><!--no nesting anchors-->
 <!ELEMENT content (#PCDATA | include | p | h1 | h2 | h3 | h4 | pre | blockquote)*><!--block elements only in top level-->
 <!ELEMENT p (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT em (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT strong (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT code (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT h1 (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT h2 (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT h3 (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT h4 (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT br EMPTY>
 <!ELEMENT img EMPTY>
 <!ELEMENT include EMPTY>
 <!ATTLIST a title CDATA #IMPLIED name NMTOKEN #IMPLIED href CDATA #IMPLIED>
 <!ATTLIST img src CDATA #REQUIRED alt CDATA #REQUIRED align (top|middle|bottom|left|right) #IMPLIED>
 <!ATTLIST include file CDATA #REQUIRED entry NMTOKEN #IMPLIED overwrite (true|false) #IMPLIED>
<!--======================================== don't touch this stuff ========================================-->
]>
<content>
	<h1> DotGNU Meet-a-thon - III </h1>
	<p class="mainbody">
	The DotGNU meet-a-thon III is being organized by the DotGNU
	developer community to meet and interact with the rest of the world.
	The DotGNU project has come into it's second year and is still 
	growing stronger still. The project has had a reasonably prosperous
	2002, and has started taking solid shape. 
	</p>
	<p class="mainbody">
	We've built a yet another Quarter million lines in the past year
	and the entire project counts to more than half-a-million lines of code 
	as of now. 
	</p>
	<p class="mainbody">
	Now, the time's come to take stock of what we did and what we missed.
	We would like to know what you think about the project and the code it
	has spewed into the ether.
	</p>
	<p class="mainbody">
	So a 36 hour IRC meet-a-thon is being conducted on irc.freenode.net
	on #dotgnu . The meet is organized as sessions of 4 hours with most major
	developers logging on according to their timezones. The meeting will be
	kicked off at 1000 UTC Saturday. It will continue for the next 36 hours 
	and key dotgnu people will remain on the channel to discuss new ideas,
	meet new people and talk about their projects.
	</p>
	<h2>Projects Being Released soon</h2>
	<ul class="mainbody">
		<li><p>DotGNU Portable.Net 0.5.0 -- foundation code, C# support.</p></li>
		<li><p>TreeCC 0.2.0 -- Compiler design tool </p></li>
		<li><p>DGEE 0.1.0 -- xmlrpc appserver </p></li>
	</ul>
	<p class="mainbody">
		We have other projects which are still are under heavy testing.
	</p>
	<ul class="mainbody">
		<li><p>DotGNU Forum -- xmlrpc client for everything DotGNU </p></li>
		<li><p>MACS@FrePort -- Authentication subsystem</p></li>
	</ul>
	<p class="mainbody">
	In more news we have people working on a Java compiler for DotGNU and
	possibly a Parrot codegen for the compiler collection soon. So come one,
	come all.
	</p>
	<h2>Other Information</h2>
	<p class="mainbody">
		The main channel shall be logged and the logs available at 
		<a href="http://ajmitch.linuxworks.co.nz/dotgnu">ajmitch.linuxworks.co.z</a>
		A channel #dotgnu-newbies will be online to answer the questions
		about the project in general. The meetathon will be covered with 
		summary reports to the developers mailing list (developer@dotgnu.org).
		The #dotgnu-auth channel will be standing by during the meet for
		any authentication questions. And last but not least , our most
		stable mirror is <a href="http://gnu.org/projects/dotgnu">GNU.org</a>.
	</p>
</content>
