<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE content
[
<!--======================================== modify but don't delete ========================================-->
 <!ENTITY base "../">
 <!ENTITY title	"DotGNU Project - Active DotGNU Proposals">
 <!ENTITY this "proposals/active.html">
 <!ENTITY maintainer "&lt;a href=&quot;http://norbert.ch/&quot;&gt;Norbert Bollow&lt;/a&gt; &lt;a href=&quot;mailto:nb@cisto.com&quot;&gt;&_lt_;nb@cisto.com&_gt_;&lt;/a&gt;">
 <!ENTITY modtime "Fri Aug 09 19:59:50 UTC 2002">
<!--======================================== modify but don't delete ========================================-->

<!--======================================== add custom entities here ========================================-->
 <!ENTITY vrshome "http://www.freesoftware.fsf.org/VRS/index.html">
 <!ENTITY vrsdev "https://savannah.gnu.org/projects/vrs/">
 <!ENTITY freportsee "http://savannah.gnu.org/projects/freport-see/">
 <!ENTITY macshome "http://macs.sourceforge.net/">
 <!ENTITY macsdev "http://sourceforge.net/projects/macs/">
<!--======================================== add custom entities here ========================================-->

<!--======================================== declared here, defined elsewhere ========================================-->
 <!ENTITY nav.snapshots "">
 <!ENTITY nav.debs "">
 <!ENTITY nav.faq "">
 <!ENTITY nav.essays "">
 <!ENTITY nav.proposals "">
 <!ENTITY nav.patent "">
 <!ENTITY nav.projects "">
 <!ENTITY nav.proposals.active "">
 <!ENTITY nav.arch "">
 <!ENTITY nav.see "">
 <!ENTITY nav.phpgw "">
 <!ENTITY nav.pnet "">
 <!ENTITY nav.pnet.lib.status "">
 <!ENTITY nav.pnet.lib.docs "">
 <!ENTITY nav.web_services "">
 <!ENTITY nav.auth "">
 <!ENTITY nav.mail.lists "">
 <!ENTITY nav.mail.pipermail "">
 <!ENTITY nav.mail.announce "">
 <!ENTITY nav.mail.developers "">
 <!ENTITY nav.mail.auth "">
 <!ENTITY nav.mail.arch "">
 <!ENTITY nav.mail.biz "">
 <!ENTITY nav.mail.website "">
 <!ENTITY misc.freedev "">
 <!ENTITY misc.gnu "">
 <!ENTITY misc.dotgnu "">
 <!ENTITY mail.gnu "">
 <!ENTITY mail.dotgnu "">
 <!ENTITY mail.rhysw "">
 <!ENTITY mail.gopal "">
 <!ENTITY mail.minten "">
 <!ENTITY mail.dnicol "">
 <!ENTITY _lt_ "">
 <!ENTITY _gt_ "">
 <!ENTITY _quot_ "">
 <!ENTITY _apos_ "">
 <!ENTITY _amp_ "">
 <!ENTITY nbsp "">
 <!ENTITY copy "">
 <!ENTITY root "">
<!--======================================== declared here, defined elsewhere ========================================-->

<!--======================================== don't touch this stuff ========================================-->
 <!ELEMENT ul (li)+>
 <!ELEMENT ol (li)+>
 <!ELEMENT dl (dt|dd)+>
 <!ELEMENT dt (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT li (#PCDATA | include | br | em | strong | code | a | img | ul | ol | dl)*>
 <!ELEMENT dd (#PCDATA | include | br | em | strong | code | a | img | ul | ol | dl)*>
 <!ELEMENT blockquote (#PCDATA | include | br | em | strong | code | a | img | ul | ol | dl)*><!--no nesting blockquotes-->
 <!ELEMENT pre (#PCDATA | include | br | em | strong | code | a)*><!--no images in pre-->
 <!ELEMENT a (#PCDATA | include | br | em | strong | code | img)*><!--no nesting anchors-->
 <!ELEMENT content (#PCDATA | include | p | h1 | h2 | h3 | h4 | pre | blockquote)*><!--block elements only in top level-->
 <!ELEMENT p (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT em (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT strong (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT code (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT h1 (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT h2 (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT h3 (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT h4 (#PCDATA | include | br | em | strong | code | a | img)*>
 <!ELEMENT br EMPTY>
 <!ELEMENT img EMPTY>
 <!ELEMENT include EMPTY>
 <!ATTLIST a title CDATA #IMPLIED name NMTOKEN #IMPLIED href CDATA #IMPLIED>
 <!ATTLIST img src CDATA #REQUIRED alt CDATA #REQUIRED align (top|middle|bottom|left|right) #IMPLIED>
 <!ATTLIST include file CDATA #REQUIRED entry NMTOKEN #IMPLIED overwrite (true|false) #IMPLIED>
<!--======================================== don't touch this stuff ========================================-->
]>

<content>
<h1>
 Active DotGNU Project Proposals
</h1>
<p>
 In this section we list DotGNU Project Proposals which are under
 active development, and which we expect to become useful pieces of
 Free Software regardless of whether they become "officially" part
 of DotGNU.
</p>
<p>
 We believe that this is the best way for realizing a huge Free
 Software project like DotGNU:  The coordinating team must give
 capable developers every freedom in creating useful contributions.
 It is possible that in some areas we may in the end have the luxury of
 choosing between two (or possibly even more) good solutions, but even
 then those solutions which don't get chosen to be "officially DotGNU"
 will be valuable pieces of Free Software that will work well with
 DotGNU.  With Free Software, the true freedom of choice will always be
 in the hands of software users, and it will not be inappropriately
 influenced by the decisions of the DotGNU Steering Committee
 concerning what is, and what isn't "officially DotGNU".
</p>
<h2>
 List of Active Project Proposals
</h2>
<ul>
 <li>
  <strong>
   DotGNU C# programming book
  </strong>
  <br />
  Original proposal by Gopal V &lt;&mail.gopal;&gt;<br />
  Peter Minten &lt;&mail.minten;&gt; posted the following ideas:
  <pre>
* To spice up the story there are some small educational tales
  explaining things in a humourous fashion. The tales feature a Sensei
  (the teacher), a student and two doofuses (I liked Rhys play so much
  that I decided to include these). The Sensei is wise but eats more
  junkfood than 20 normal hackers and is often very sarcastic. The student
  is the typical nerd that tries his best. The doofuses are besides very
  dumb (when they walk into a village the average IQ of that village drops
  5 points) also very arrogant and have VERY big egos (and have I
  mentioned that they overuse hacker jargon whenever possible). Mix this
  with some programming concepts and you get a nice educational comedy
  :-).

* The book could have the following parts:

I    Installation, compilation, how to use pnet, etc
II   The basics of the language (variables, methods, classes)
III  Advanced use of the language (inheritance, overloading, attributes)
IV   In depth look at basic classes (object, String, Int32, Array)
V    In depth look at various important parts of the library (Net, 
     Sockets, IO)
VI   Introduction of important dotgnu libs
VII  In depth look at important dotgnu libs
VIII How to make good programs (style, how to debug, where to install
     files)
IX   Appendixes (Philosophy, explanation of the pnet tools (ilnative,
     ildb, ilasm), the answers to exercises)

* The book should also have a lot of exercises as training.

* A good lot of graphics would be nice.
  </pre>
 </li>
 <li>
  <strong>
   Virtual Remote Server
  </strong>
  <p>
   <a href="&vrshome;">Virtual Remote Server</a> is a pure p2p server
   cluster that provides several of the most important advantages
   of a centralized server. Those are
  </p>
  <ol>
   <li>
    a persistent, easily accessible net presence, and
   </li>
   <li>
    a consistent response to requests. In other words, a common and
	manageable database.
   </li>
  </ol>
  <p>
   VRS is an alternative to the "SEE/DEE" approach which is more based on
   a centralized ASP model (potentially a commercial one) in which the
   users have an escape clause, and can remove their data if disgruntled
   and provide it from their own local machine.
  </p>
  <p>
   VRS takes the opposite approach.  It starts with the
   local machine, where the local client/server node
   software runs (called the Local Data Server LDS). 
   These individual nodes then aggregate, forming the VRS
   itself.  I think commercial participation in such a
   system is possible by providing scaled up node
   resources, a branded port of entry into a VRS cluster
   and administrative services.   But that business will
   always be at the mercy of their subscribers, not the
   subscriber at the mercy of the business.  The
   subscriber can always pull their registered components
   out of the system.  Ever more so, if enough
   subscribers also pull their nodes, the offending
   businesses cluster server literally evaporates.  They
   HAVE to play nice.
  </p>
  <p>
   VRS will be developed at Savannah:
   <a href="&vrsdev;">&vrsdev;</a>
  </p>
 </li>
 <li>
  <strong>
   FrePort
  </strong>
  <p>
   The Freport Project wishes to create a plug-in module for the
   <a href="&nav.see;">Secure Execution Environment daemon (SEE)</a>. The
   module will implement secure and private, named data storage and
   retrieval and will be useful for authorization, authentication, or
   general data storage.  The plug-in will perform many of the functions
   of remote open LDAP, with similar functionality to proprietary
   solutions such as Microsoft's Passport.
  </p>
  <p>
   Unlike other products, primary importance is placed on providing data
   and metadata security, user privacy and anonymity, and system
   adaptability, while not compromising transportability across devices and
   point of access. The Freport system is not a unitary system, but instead
   possesses it's own plug-in system designed to adapt the technology to a
   variety of data storage mechanisms and networking systems.
  </p>
  <p>
   The project is currently in the architectural development stage.
  </p>
  <p>
   For more information, please refer to the <a href="&freportsee;">Savannah
   project space</a> of this project.
  </p>
 </li>
 <li>
  <strong>
   macs
  </strong>
  <p>
   <a href="&macsdev;">macs</a> aims to be a general
   purpose authentication, authorization, and user-profiling backend,
   frontendable by anything. macsDG will be a DotGNU-specific project to
   integrate macs with DotGNU, by creating macs clients, and extending macs
   servers, to plug into the <a href="&nav.see;">Secure Execution
   Environment daemon (SEE)</a>. These clients will protect the SEE via the
   servers. See the README on the <a href="&macshome;">macs page</a>
   for an overview. (The SEE could be in the ??? box in the diagram.)
  </p>
  <p>
   The plan for the time being is to continue development on a macs
   prototype until it is fully featured and functional. At that time, the
   macsDG project will begin writing macs clients for the SEE, while the
   macs servers are refactored/rewritten. Finally, macsDG will extend the
   new (non-prototype) macs servers, adding a compile-time option for making
   SEE plugins out of them.
  </p>
 </li>
 <li>
  <strong>
   Cashbox
  </strong>
  <p>
   David Nicol, who set up <a href="http://tipjar.com">tipjar.com</a> in
   1996, will GPL a catalog/order customer-account system, called "cashbox."
   If you would like to help with it please contact him at
   <a href="mailto:&mail.dnicol;">&mail.dnicol;</a>
  </p>
 </li>
</ul>
</content>